# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rcc method implementation for knapsack dynamic programming
#' 
#' @param W numeric vector indicating maximum capacity of knapsack
#' @param wt numeric vector indicating weight of individual element in the datase
#' @param val value of individual element in the dataset
#' @param n number of objects in the data set
#' @return a matrix with sequence of all weights and values.
#' @export 
knapSackdynamic_cpp <- function(W, wt, val, n) {
    .Call(`_Lab6Assignment_knapSackdynamic_cpp`, W, wt, val, n)
}

